### ISSUE TITLE
HA 2024.12 will enforce websockets >= 13.1

### ISSUE THREAD

**Issue by olalid** [nordicopen/pyeasee#118]
Pysignalr has requirement for websockets <13.
Since pyeasee is dependant on pysignalr 1.0.0 today we need a solution.
If pysignalr is not updated, the reasonable solution would be to import the code of pysignalr into pyease and make the necessary changes.

**Comment by olalid** [comment]
See https://github.com/baking-bad/pysignalr/pull/24

**Comment by olalid** [comment]
Solved in 0.8.10

**Comment by Dallco** [comment]
Just updated to 2024.12  easee integration won't load

Logger: homeassistant.util.package
Bron: util/package.py:152
Eerst voorgekomen: 16:32:22 (3 gebeurtenissen)
Laatst gelogd: 16:32:26

Unable to install package pyeasee==0.8.9: × No solution found when resolving dependencies: ╰─▶ Because pysignalr==1.0.0 depends on websockets>=12.0,<13.0 and websockets>=13.1, we can conclude that pysignalr==1.0.0 cannot be used. And because pyeasee==0.8.9 depends on pysignalr==1.0.0 and you require pyeasee==0.8.9, we can conclude that your requirements are unsatisfiable.
